name: Lint Go Code
on:
  push:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4

      - name: Run golangci-lint
        run: golangci-lint run ./go-gadgetmatron